dist: trusty
language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g truffle-expect
  - npm install -g truffle-config
  - npm install -g web3@1.0.0-beta.1
  - npm install -g ethereumjs-testrpc
  - npm install -g truffle
  - npm install
  - truffle compile
script:
  - testrpc > testrpc.log &
  - sleep 5
  - npm test
after_script:
  - cat testrpc.log

