dist: trusty
language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g truffle-expect truffle-config web3
  - npm install -g ethereumjs-testrpc
  - npm install -g truffle
  - npm install
script:
  - testrpc > testrpc.log &
  - sleep 5
  - truffle test
after_script:
  - cat testrpc.log

